# Fichier de paramètres 
---


# les répertoires pour l'installation Oracle
  oracle_stage: /u01/stage
  oracle_rsp_stage: "{{ oracle_stage }}/rsp"
  oracle_version_db: 12.1.0.2
  oracle_base: /u01/app/oracle
  home: dbhome_1
  oracle_home: "{{ oracle_base }}/product/{{ oracle_version_db }}/{{ home }}"


# paramètres du noyau
  oracle_sysconfig:
      - { name: kernel.shmall, value: "{{ ((0.4 * ansible_memtotal_mb)*1024)|round|int  }}" }
      - { name: kernel.shmmax, value: "{{ ((0.5 * ansible_memtotal_mb)*1024)|round|int  }}" }
      - { name: kernel.shmmni, value: 4096 }
      - { name: kernel.sem, value: "250 32000 100 128" }
      - { name: fs.file-max, value: 6815744 }
      - { name: fs.aio-max-nr, value: 1048576 }
      - { name: net.ipv4.ip_local_port_range, value: "9000 65500" }
      - { name: net.core.rmem_default, value: 262144 }
      - { name: net.core.rmem_max, value: 4194304 }
      - { name: net.core.wmem_default, value: 262144 }
      - { name: net.core.wmem_max, value: 1048576 }
      - { name: vm.nr_hugepages, value: "{{ (((percent_hugepages/100) * ansible_memtotal_mb)/2)|round|int  }}" }

# Security limits
  oracle_seclimits:
      - "* soft nproc 2047"
      - "* hard nproc 16384"
      - "* soft nofile 1024"
      - "* hard nofile 65536"
      - "* soft memlock {{ ((0.9 * ansible_memtotal_mb)*1024)|round|int }}"
      - "* hard memlock {{ ((0.9 * ansible_memtotal_mb)*1024)|round|int }}"
      - "* soft stack 10240"
      - "* hard stack 32768"
      - "* soft core  unlimited"
      - "* hard core  unlimited"


# Fichier de paramètres : packages ORACLE

  oracle_packages:
      - bind-utils
      - binutils
      - btrfs-progs
      - cloog-ppl
      - compat-libcap1
      - compat-libstdc++*i686
      - compat-libstdc++-33
      - cpp
      - ethtool
      - gcc
      - gcc-c++
      - glibc
      - glibc*i686
      - glibc-devel
      - glibc-headers
      - kernel-headers
      - kmod-oracleasm
      - ksh
      - libX11
      - libX11*i686
      - libXau
      - libXau*i686
      - libXext
      - libXi
      - libXp
      - libXt
      - libXtst
      - libaio
      - libaio*i686
      - libaio-devel
      - libaio-devel*i686
      - libgcc
      - libselinux-python
      - libstdc++
      - libstdc++*i686
      - libstdc++-devel
      - libstdc++-devel*i686
      - libtool-ltdl
      - libxcb
      - libxcb*i686
      - make
      - module-init-tools
      - mpfr
      - ncurses-devel
      - ncurses-libs
      - nfs-utils
      - nscd
      - ntp
      - openssh-clients
      - oracleasm-support
      - parted
      - ppl
      - procps
      - readline
      - readline-devel
      - sysstat
      - twm
      - unixODBC
      - util-linux-ng
      - vim-enhanced
      - xdpyinfo
      - xfsprogs
      - xorg-x11-utils
      - xorg-x11-xauth
      - xorg-x11-xinit
      - xsetroot
      - xterm
