---
- name: Host configuration 
  hosts: all
  user: root

  roles:
   - { role: configure-host-oel6, when: "ansible_distribution_major_version == '6'" }
   - { role: configure-host-oel7, when: "ansible_distribution_major_version >= '7'" }
#   - install-oracle-sw

