---
# installation de l'utilitaire rlwrap pour oracle

  - name: Copy du rpm rlwrap vers le serveur
    copy: src=rlwrap-0.44-1.el8.x86_64.rpm dest=/tmp/rlwrap-0.44-1.el8.x86_64.rpm owner=root mode=644

  - name: Install rlwrap rpm from a local file
    yum:
      name: /tmp/rlwrap-0.44-1.el8.x86_64.rpm
      state: present

  - name: suppression du rpm rlwrap du serveur
    file: path=/tmp/rlwrap-0.44-1.el8.x86_64.rpm state=absent